
name: 'Terraform'
on:
  push:
    branches:
    - test
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: task
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Terraform Init
      run: cd task1/terraform && terraform init
    - name: Terraform Format
      run: cd task1/terraform && terraform fmt -check
    - name: Terraform Plan
      run: cd task1/terraform &&terraform plan -input=false
    - name: Terraform Apply
      run: cd task1/terraform &&terraform apply -auto-approve -input=false
