
name: 'Terraform'
on: []
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: task
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Terraform Init
      run: cd task1/terraform && terraform init
    - name: Terraform Format
      run: cd task1/terraform && terraform fmt -check
    - name: Terraform Plan
      run: cd task1/terraform &&terraform plan -input=false
    - name: Terraform Apply
      run: cd task1/terraform &&terraform apply -auto-approve -input=false
